### ISSUE TITLE
4.0.0 with env based setup fails to start

### ISSUE THREAD

**Issue by jinnatar** [shlinkio/shlink-web-client#1046]
### shlink-web-client version

4.0.0

### How do you use shlink-web-client

Docker image

### Current behavior

```
docker run --rm -it -e SHLINK_SERVER_URL="https://go.example.com" -e SHLINK_SERVER_API_KEY=foo shlinkio/shlink-web-client:4.0.0
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-shlink-servers-json.sh
/docker-entrypoint.d/30-shlink-servers-json.sh: line 11: can't create /usr/share/nginx/html/servers.json: Permission denied
```

### Expected behavior

Start, like versions prior to 4.0.0 did with the same config.

### How to reproduce

```
docker run --rm -it -e SHLINK_SERVER_URL="https://go.example.com" -e SHLINK_SERVER_API_KEY=foo shlinkio/shlink-web-client:4.0.0
```

**Comment by jinnatar** [comment]
Looking at the Dockerfile, I'd imagine a simple `chown $UID /usr/share/nginx/html` or a more targeted one somewhere around https://github.com/shlinkio/shlink-web-client/blob/develop/Dockerfile#L15 would take care of the issue, as it's too late to do that in the entrypoint already running as `101`.

**Comment by acelaya** [comment]
> Looking at the Dockerfile, I'd imagine a simple chown $UID /usr/share/nginx/html or a more targeted one somewhere around https://github.com/shlinkio/shlink-web-client/blob/develop/Dockerfile#L15 would take care of the issue

Yep, I think that should do. Want to contribute a PR?

**Comment by jinnatar** [comment]
Sure, lemme run a quick test to make sure that's the root cause.

**Comment by Stunt0265** [comment]
What's the fix for this?

**Comment by acelaya** [comment]
@Stunt0265 see linked ~issue~ PR

**Comment by jinnatar** [comment]
As a mitigation before 4.0.1 if you want to use the latest version, you could volume mount in servers.json instead of env config, the entrypoint just generates it based on the env variables.

**Comment by acelaya** [comment]
shlink-web-client 4.0.1 has now been released, including this fix.
