### ISSUE TITLE
Starting version 4, shlink-web-client on docker returns ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by kotoxie** [shlinkio/shlink-web-client#1052]
### shlink-web-client version

stable

### How do you use shlink-web-client

Docker image

### Current behavior

TCP connections immediately gets refused and closed

### Expected behavior

I should be granted the HTTP site

### How to reproduce

spin up a shlink-web-client container on ARM

** Important note - everything works on 3.10.2

**Comment by acelaya** [comment]
If you check the changelog, you'll see the docker image no longer exposes port 80, but 8080. Make sure you update the mapping.
