### ISSUE TITLE
Can't specify device specific URLs

### ISSUE THREAD

**Issue by Zernov-A** [shlinkio/shlink-web-client#1093]
### shlink-web-client version

4.0.2

### How do you use shlink-web-client

Docker image

### Current behavior

After upgrading Shlink to version 4.0.2, I am unable to specify device-specific URLs using shlink-web-client (version 4.0.1). It seems that the API has been changed, requiring revisions to shlink-web-client.
This functionality worked fine with Shlink version 3.7.4 and below.

### Expected behavior

I expect to have the ability to specify device-specific URLs using shlink-web-client with new versions of Shlink.

### Minimum steps to reproduce

Attempt to specify device-specific URLs using shlink-web-client (Shlink version 4.0.2).

**Comment by acelaya** [comment]
Yes, this was documented here https://github.com/shlinkio/shlink/blob/develop/UPGRADE.md#changes-in-url-shortener (see the last point there). In short, shlink-web-client does not yet support Shlink 4.0.0

There's [work in progress](https://github.com/shlinkio/shlink-web-component/issues/271) to support the new redirect rules which handle device-specific redirects in Shlink 4
