### ISSUE TITLE
"Copy Short URL" button doesn't work

### ISSUE THREAD

**Issue by Zernov-A** [shlinkio/shlink-web-client#1104]
### shlink-web-client version

4.1.0

### How do you use shlink-web-client

Docker image

### Current behavior

The "Copy Short URL" button has stopped functioning starting with version 4.1.0. It was working correctly in version 4.0.1.
Web-Browser: Google Chrome 122.0.6261.129

### Expected behavior

The "Copy Short URL" button should copy the Short URL as expected.

### Minimum steps to reproduce

Attempt to click the "Copy Short URL" button on the overview page or list-short-urls page.

**Comment by acelaya** [comment]
The most modern [clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) (which is the one used by shlink-web-client 4.1) requires [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), which means, HTTPS is mandatory unless serving from localhost or 127.0.0.1

I suppose that is not the case for you if you are self-hosting shlink-web-client

You can test https://app.shlink.io, and you'll see it works there.

**Comment by Zernov-A** [comment]
Thank you for answer!
Yes, it works with HTTPS, and localhost (with http).
