### ISSUE TITLE
Public Shlink web client broken

### ISSUE THREAD

**Issue by masoncfrancis** [shlinkio/shlink-web-client#1148]
### shlink-web-client version

latest

### How do you use shlink-web-client

https://app.shlink.io

### Current behavior

Receiving `502 Bad Gateway` error when visiting public site at https://app.shlink.io

![Captura de pantalla 2024-04-18 203944](https://github.com/shlinkio/shlink-web-client/assets/19189385/42083935-6aa3-4324-84c3-6b722e7b13f9)

### Expected behavior

I expected to be able to access the web app

### Minimum steps to reproduce

Visit https://app.shlink.io

**Comment by acelaya** [comment]
Sorry for the inconvenience. It should be back now.
