### ISSUE TITLE
Add pin grouping to the map view for cities

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink-web-client#119]
The cities map is basically un-usable due to the sheer number of pins on high click links, they need to dynamically group/paginate

https://i.imgur.com/LZnxWJD.png

**Comment by acelaya** [comment]
There's never more than one pin per city. If the link has received visits from lots of different cities, you will probably see a lot of pins, but also, with very little zoom.

Zooming in should mitigate the problem.

**Comment by jakkuh** [comment]
I wasn't saying there was more than 1 pin per city, but when you zoom out at all and can see all of the several hundred or thousand cities, it's too much for any web browser to handle.

My suggested feature would be to group nearby cities together when you zoom out and then display a number (representing the number of cities grouped) on the pin.

It's really not a high priority but thought it would be kind of cool.

**Comment by acelaya** [comment]
Ah, ok, I see your point now.

Your suggestion is actually cool. I will try to investigate it and see how complex would it be.
