### ISSUE TITLE
Rename "Custom Slug" to "Custom Shlug"

### ISSUE THREAD

**Issue by tigunia-martin** [shlinkio/shlink-web-client#1197]
### Summary

In the webclient, we'd like to have the "Custom Link" text renamed to "Custom Shlug" to match the nomenclature of Shlink
Before:
![slug](https://github.com/shlinkio/shlink-web-client/assets/134078129/55cfcc12-a4f9-478c-b31d-e8096d86351f)
After:
![shlug](https://github.com/shlinkio/shlink-web-client/assets/134078129/d28f23ed-a753-4f95-93a6-b5d08f55de3a)

### Use case

This rename of text fits Shlink much better.

**Comment by acelaya** [comment]
WTF 😅
