### ISSUE TITLE
Make URLs in the "Visited URL" column clickable

### ISSUE THREAD

**Issue by mdrxy** [shlinkio/shlink-web-client#1274]
### Summary

"Visited URLs" at `/non-orphan-visits/list` are not hyperlinks. My request is to convert them to hyperlinks.

### Use case

This would save users time and allow them to navigate to the URL without needing to select the text, copy, open a new tab, paste, and then enter.

**Comment by acelaya** [comment]
That value is mainly informative. What's the context for you to need to visit the URL that was visited by a user? Wouldn't that generate incorrect visit stats for you?

**Comment by mdrxy** [comment]
The context would be investigating quickly to see what it is pointing to - perhaps to mitigate incorrect visit stats (which in my eyes would be fine sacrificing), the `href` would point to the underlying long URL?

**Comment by acelaya** [comment]
See [my comment here](https://github.com/shlinkio/shlink-web-client/issues/1275#issuecomment-2306432171).

Once the capability referenced there is implemented, we can enhance this list so that you can cross-reference visits with the short URL that produced them.

I'll close this for now.
