### ISSUE TITLE
subdomain redirecting 

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink-web-client#130]
hello i want to host the shlink web client by myself, but i got problem that i just redirected to the domain that i just setup before for the shlink url short service (so its just say "404 page not found" with shlink footer in the bottom, i want to host this client in the same server but in a subdomain..

did i just get wrong with my server block and virtual host on my nginx or there is a config in the short url service that rule the domain maybe ?

so the line is : 

short url service = example.com www.example.com
web client = app.example.com

I download this https://github.com/shlinkio/shlink-web-client/releases/download/v2.0.3/shlink-web-client_2.0.3_dist.zip and just extract it..

and configure the server block

i just want to get clear, that i miss something in my config or there just some config in short url service that doing this ?

**Comment by acelaya** [comment]
It should be possible to do what you want. Neither shlink or shlink web client do anything regarding the domain.

In fact, both of them ignore the domain. Shlink just asks for the domain to be able to generate correct URLs, but it does not use it while serving HTTP requests.

Maybe if you share your shlink and shlink-web-client nginx configs here I could try to help you.

**Comment by captainAldi** [comment]
perhaps just me can't cofig the vhost properly..

this is my server bloc for example.com and i add the server block for subdomain app.example.com inside it

`
## For app.example.com subdomain
server {
        listen 80;
        listen [::]:80;
        root /path/to/Shlink-web/public;
        index index.html;
        server_name app.example.com;
}


server {
    server_name example.com www.example.com;

    root /path/to/Shlink/public;
    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
    }

    location ~ /\.ht {
        deny all;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } #managed by Certbot


    server_name example.com www.example.com;
    listen 80;
    return 404; # managed by Certbot

}

`

or perhaps just my subdomain not pointing properly to my dns / ip  ?

**Comment by captainAldi** [comment]
**Update..**

i'm able to navigate to my subdomain
but it just show white blank page.. 

i create the docroot to shlink-web-client-master/public/index.html

did i make it right ?

**Comment by captainAldi** [comment]
**Update Again**

my webClient and Url short service just online.. Thanks.. 👍 

maybe you could please write the documentation about deploying the webClient more clearly
like
1) must build it again
2) set the homepage
etc

it just my opinion..

Thanks btw 👍

**Comment by captainAldi** [comment]
**Ask again**

https://app.shlink.io/server/

that the link from official web

but, when i put to my server itu just shown my full path server

how can i avoid that ?

**Comment by acelaya** [comment]
>maybe you could please write the documentation about deploying the webClient more clearly
>like
>
> . must build it again
> 2. set the homepage
> etc
> it just my opinion..

That's already documented: https://github.com/shlinkio/shlink-web-client#serve-project-in-subpath

> https://app.shlink.io/server/
>
> that the link from official web
>
> but, when i put to my server itu just shown my full path server
>
> how can i avoid that ?

I'm not completelly sure that I'm understanding your question, but if you are asking if it is possible to avoid the path to change, it is not.
