### ISSUE TITLE
where to chage text in page 

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink-web-client#131]
where can i edit the page like index.html ?

that have an id root ?

**Comment by acelaya** [comment]
I'm not sure if I follow you. What do you want to change?

**Comment by captainAldi** [comment]
text in dasboard and perhaps i want to add some images in side menu... where can i edit that ?

**Comment by acelaya** [comment]
Understood. This is a react+redux app, so you probably need to be a little bit familiar with that.

* https://reactjs.org
* https://redux.js.org

Components are in the src folder.
