### ISSUE TITLE
Disable PWA precaching to allow proper forward auth

### ISSUE THREAD

**Issue by noahstreller** [shlinkio/shlink-web-client#1322]
### Summary

Add an environment variable to the web client, which disables the PWA precaching.

### Use case

I would like to use the web client with preconfigured servers using Docker Compose. Since it does not have inbuilt authentication, I secure it with a forward auth setup. 

This works well for the first login, but because the PWA gets precached, logging out of the identity provider does not affect shlink, and the user is still able to use the web client until the cache is cleared.

**Comment by acelaya** [comment]
It's not possible to have conditional behaviors on this app, because it runs 100% in the browser.

For more advanced cases like this, I'm preparing another app with its own backend https://github.com/shlinkio/shlink-dashboard
