### ISSUE TITLE
Feature Request: New line graph for daily hits

### ISSUE THREAD

**Issue by poblabs** [shlinkio/shlink-web-client#149]
Another feature request! 

Is it possible to add a line chart which shows the number of hits per day? Or hourly? Or something along those lines. It would be great to see the amount of activity as a line chart over the time span. 

(I'd fork and try it but I don't understand the framework you're using)

Thanks!

---

See #198

**Comment by acelaya** [comment]
Yes, I think it's something useful, but it might require some additions to shlink's API as well, so it could take longer.

**Comment by poblabs** [comment]
No problem! The charts are what makes shlink great. I think they should be showcased even more 😃 

Also, is it possible to add a quicker way to get to the stats? Maybe add a hyperlink to "Visits" numbers to bring you to the stats page? A little faster than using the menu itself. 

Anyways, thanks again and no rush!

**Comment by acelaya** [comment]
Hey @poblabs.

It's been a while, but this feature is going to land shlink-web-client v2.5.0

Here you can have a peek of how it will look: https://youtu.be/ObsHEHOocFw
