### ISSUE TITLE
Default sort short URLs list by Created at DESC

### ISSUE THREAD

**Issue by Haocen** [shlinkio/shlink-web-client#150]
When listing the short URLs, default to order by most recently created on the top.

**Comment by acelaya** [comment]
I would prefer to keep it as it is.

Flipping the ordering is a matter of clicking the table header.

**Comment by ymage** [comment]
Maybe make it as configurable ?

I definitely prefer as `Created at DESC` and I keep clicking (twice !!!) to get that order.
One, to select the criteria (defaulting to ASC)
Secund, to change to DESC

I really don't care to look at my 2013 shortlinks first (yeah, imported from YOURLS)

**Comment by acelaya** [comment]
I guess it makes sense to see the most recent links first. I will change it, and consider making it configurable too.
