### ISSUE TITLE
The official docker build failed to configure nginx with SPA specific settings

### ISSUE THREAD

**Issue by Haocen** [shlinkio/shlink-web-client#155]
Currently if a user try to refresh or visit the page for a specific server directly, for example:
https://example.com/server/455c8f83-42da-47eb-85b1-8992dadf388a/list-short-urls/1

A 404 not found page will be served because nginx is looking for path `/server/455c8f83-42da-47eb-85b1-8992dadf388a/list-short-urls` with the file `1` in it.

Nginx configuration should be changed in order to address this.

**Comment by acelaya** [comment]
I think I have experienced that in the past (with other SPA with client-side HTML5 routing as well).

I will check the PR you have provided. Thanks!

**Comment by acelaya** [comment]
I have just managed to reproduce it (chrome does something weird and apparently mitigates it, but I made it with `wget`).
