### ISSUE TITLE
Make pagination controls display only the amount of pages that fit one row

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink-web-client#157]
Currently when paginating the cities tab in analytics, if you have a large number of unique cities, this happens: https://i.imgur.com/RFbIvUj.png

That's a 150k visit's link.

I think something like the way Google's search results handles it would work well. https://i.imgur.com/TZqBXEI.gifv

It would also be helpful to display like "Page x of y" so you know how far the list extends. 'x' being the current page number, with 'y' as the total number of pages.

**Comment by acelaya** [comment]
@tivyhosting how does this look.

![ezgif-3-e629c040e360](https://user-images.githubusercontent.com/2719332/65384621-929f8600-dd24-11e9-9fb0-21266d5a12f0.gif)

This ensures only a few page controls to be rendered at the same time, but you also know how many pages there are.

*(I just set an option with 2 items per page to force a lot of pages to be rendered, but that won't be part of the release)*
