### ISSUE TITLE
Update Header from static html

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#170]
https://github.com/shlinkio/shlink-web-client/blob/d9097896f62d9efbead0251818494cf85ddac446/public/index.html#L14-L19

url at the favicons is always: 
`/icons/shlink-[XX].png` 
but should be
`/icons/icon-[XX]x[XX].png` 

as the Files `/icons/shlink-[XX].png` does not exist.

**Comment by acelaya** [comment]
You are totally right!

Do you want to open a pull request to fix it?

**Comment by the-hotmann** [comment]
Have done so
https://github.com/shlinkio/shlink-web-client/pull/171
