### ISSUE TITLE
User / Password login

### ISSUE THREAD

**Issue by benhartwich** [shlinkio/shlink-web-client#172]
#### Summary

I´m self hosting this web client and I´ve set a json config for the server connection. Unfortunatelly I cannot control access except with the nginx allow and deny rules. Is there any changed to get an user / password based login?

**Comment by acelaya** [comment]
Hey @benhartwich 

The "servers.json" feature was designed for people self hosting the app to be able to define a set of servers that are automatically available for everyone.

If you don't want some servers to be available for some users, the recommendation is to avoid adding them there.

Having user authentication would require a backend, and shlink-web-client is currently designed as a fully static client-side app, so it's sadly not possible to implement that feature right now.

I might consider something in the future, but it's not a priority for now, so I can't give you an ETA.

Thanks for the understanding.
