### ISSUE TITLE
Calls per Link on hour/day/week base

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#198]
I think links should be much easier to anaylse.

I personally miss something that shows me the calls per hour/day/week/month. something like this:

https://apexcharts.com/javascript-chart-demos/line-charts/data-labels/ (btw I love Apex charts, but chartJS is good aswell)

Or something we know from CloudFlares Dashboard:
![Chart](https://user-images.githubusercontent.com/17692860/73503282-2c122f00-43cc-11ea-8e3d-09601c5eaadb.PNG)

**Comment by acelaya** [comment]
Sure. Those requests make sense (in fact this has already been asked in the past https://github.com/shlinkio/shlink-web-client/issues/149), so they will be done.

**Comment by acelaya** [comment]
Hey @MartinH0, I will have to move this to next release. This needs a bit of investigation (I want to check if it makes sense to do this on Shlink side instead of the web client), and I don't want to delay releasing v2.4

Sorry for the inconvenience.

**Comment by the-hotmann** [comment]
Thats completely ok, as this is a free open source tool noone does have any entitlements or anything else. Also implementing a chart which is showing the usage of any link on time-base is not to easy to implement so this is totaly ok :)

**Comment by acelaya** [comment]
Took me a while to get time to work on this, but it's looking good.

https://youtu.be/ObsHEHOocFw

**Comment by the-hotmann** [comment]
That looks good!
Just one little thing: do you have to hit the dots to shot the stats or is it enough to hit the Y-Coordinate to display all of the infos on this Y-Coordinate?
Do you know what I mean?

I mean something like this:
![Apex Charts](https://user-images.githubusercontent.com/17692860/83329129-f3a23500-a287-11ea-92c0-c25f123e2e1c.png)

Is that possible?

**Comment by acelaya** [comment]
When I captured the video, you had to hover on the dot to display the tooltip, but then I have changed it so that it gets displayed when hovering over the whole vertical line.
