### ISSUE TITLE
Edit long URL on Edit Metadata

### ISSUE THREAD

**Issue by tedo-develop** [shlinkio/shlink-web-client#210]
#### Shlink web client version

* Version: Latest docker image
* Docker image, self-hosted

#### Summary

Hello @acelaya,

first of all great work!

But i have a question. Is it possible to edit the long url after creating a short url?
I have only the chance to edit the **enabled since, enable until and max number of visits** metadata.

Is there a way to edit the long url?

**Comment by acelaya** [comment]
Hey @tedo-develop 

Thanks for the feedback :)

I'm afraid it is currently not possible, but the plan is to get it implemented on next release https://github.com/shlinkio/shlink/issues/521

You can subscribe to that ticket.
