### ISSUE TITLE
Adding Client & Server App version info

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#213]
I think it would be cool to be able to see which version of the Web-Client and of the Shlink Application one is using.

Web-Client version is always the same but if I log in into another Server the Server should tell the Web-Client which version he is running on so people know when they use outdated versions.

I just quickly made a little demo how I think it could look.

ALL:
![Shlink version info All](https://user-images.githubusercontent.com/17692860/75798869-7f82ee80-5d77-11ea-9864-878d4e776327.png)

Zoomed:
![Shlink version info](https://user-images.githubusercontent.com/17692860/75798875-814cb200-5d77-11ea-8284-5f5861d42d8e.PNG)

If you like it and want to implement it I just give you the Code here:

1. append (to last) in the div with the class `"shlink-container"` a `<div>` with a class `vInfo`.
2. add text with App info.
3. add the CSS:
```
.vInfo{
    position: absolute;
    right: 1em;
    bottom: 1em;
    font-size: 12px;
    color: #bbb;
}
```

Ofc you can edit it so it fits however you think is the best.

But atm I dont know if Shlink itself even provides the information about its own app (Server) version info. But at least I could not find it here ([LINK](https://api-spec.shlink.io/?version=v2.0.5#/))
Client version info can be hardcoded in each web-client version in the html.

Would look like this:

![Shlink Version Info HTML](https://user-images.githubusercontent.com/17692860/75799863-01274c00-5d79-11ea-8d72-be7a59918a45.PNG)

code to be added: `<div class="vInfo">Client: v2.3.1 | Server: v$server_version </div>`

**Comment by acelaya** [comment]
This makes a lot of sense, and it's easily doable, because shlink-web-client is already fetching this information in order to dynamically show/hide components based on the server's capabilities.

**Comment by acelaya** [comment]
@MartinH0 I have just implemented it and it will be part of the next release.
