### ISSUE TITLE
Cannot delete invalid servers

### ISSUE THREAD

**Issue by cdalexndr** [shlinkio/shlink-web-client#225]
#### Shlink web client version

* Version: docker shlinkio/shlink-web-client:latest
* How do you use shlink-web-client: Docker image

#### Summary

Cannot delete invalid servers.

#### Current behavior

Adding an invalid server results in:
```
Oops! Could not connect to this Shlink server.
Make sure you have internet connection, and the server is properly configured and on-line.
```
The button to delete the server is inside the server dashboard which cannot be accessed.
The homepage remains polluted with invalid server entries.

#### Expected behavior

Some mechanism to delete invalid servers.
The delete button should be placed on homepage beside the server entry.

#### How to reproduce

Add an invalid server url.

**Comment by acelaya** [comment]
Nice catch. This validation is quite new and not yet released as part of a stable version.

I will fix it.

Thanks!

**Comment by cdalexndr** [comment]
@acelaya shouldn't be a docker tag `stable` like `shlinkio/shlink` has?
Currently there are only `latest` and version tags.

**Comment by acelaya** [comment]
@cdalexndr you are completelly right. I have just pushed the `stable` tag for shlinkio/shlink-web-client docker image.

It will be automatically updated every time a new version is released.

**Comment by acelaya** [comment]
Hey @cdalexndr. I'm about to merge a PR which adds the next things:

* Existing servers can now be editted. A new button has been added to the main dashboard in the left menu
![image](https://user-images.githubusercontent.com/2719332/76702275-d8804a00-66c8-11ea-978b-cb696c0f0356.png)
* When a server cannot be reached, the error page now shows two options to delete or edit the server, directly from there.
![image](https://user-images.githubusercontent.com/2719332/76702306-1ed5a900-66c9-11ea-98f3-a939fb580c1c.png)

This should fix this issue.
