### ISSUE TITLE
Pagination not looks good, it show all the number

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink-web-client#240]
#### Shlink web client version

* Version: 2.3.1
* How do you use shlink-web-client: self-hosted

#### Summary

first i used v2.0.3 then i update it to v2.3.1

i don't know if this normal or not, i mean should pagination look like this ?

![image](https://user-images.githubusercontent.com/48024406/78699550-474e6d00-792e-11ea-860a-00a598808d85.png)

i do have many short url, so please let me know this is normal or not.. i just thing pagination looks like one line not multiline like that and with the number change if we get to the next section .

Thankyou 🙏

**Comment by acelaya** [comment]
Hello @captainAldi 

I'm afraid yes, that's how it looks on latest stable version. However, a fix for that is already implemented and will be part of v2.4.0, which will be released this week or next one.

This is how it will look then:

![Screenshot_20200407-210317](https://user-images.githubusercontent.com/2719332/78709075-5a077880-7913-11ea-8741-8ba69401cdbe.png)

This paginator will only display first and last page, and those closest to the active one, being dynamically generated based on the active page.

**Comment by acelaya** [comment]
You can see another example here:

![image](https://user-images.githubusercontent.com/2719332/78713909-43fdb600-791b-11ea-98bf-fc16f542086d.png)

**Comment by captainAldi** [comment]
That's Great ! 

Thankyou
