### ISSUE TITLE
last page table / short url list not looks good

### ISSUE THREAD

**Issue by captainAldi** [shlinkio/shlink-web-client#249]
#### Shlink web client version

* Version: 2.4.0
* How do you use shlink-web-client: self-hosted

#### Summary

after i upgrade from 2.3.1 to 2.40 i face this issue 

![image](https://user-images.githubusercontent.com/48024406/79301018-9b4ee800-7f12-11ea-942e-6b8b02ea62c3.png)

it's it normal or not ? 
i think before upgrade it's doesn't look like that.. it's just "normal" table / list

and this is just happen in last page, one page before last page it's just normal like before

i mean, short url colum uses mutch space and long url colum use less space..

btw the pagination its look's great !
Big Thanks 😄

**Comment by acelaya** [comment]
It's weird that it decides to assign so little space to that column. However, I think it's related with the fact that there's only one item on this page.

I will investigate it.

**Comment by captainAldi** [comment]
i think my short url is just too long..😂 

it make sense right ? (but before i upgrade it just looks good.. yeah never mind.. )
it still a wonderful relase, i just edit my short url then

sorry🙏

you can close the issue
