### ISSUE TITLE
Assets under v2.4.0 contain v2.3.0

### ISSUE THREAD

**Issue by IIIEII** [shlinkio/shlink-web-client#259]
#### Shlink web client version

* Version: 2.4.0
* How do you use shlink-web-client: self-hosted

#### Summary

Source code assets:
https://github.com/shlinkio/shlink-web-client/archive/v2.4.0.zip
https://github.com/shlinkio/shlink-web-client/archive/v2.4.0.tar.gz
contain source code of 2.3.0 version

#### Current behavior

In package.json of source code asset I see:
"version": "2.3.0"

#### Expected behavior

I'm expecting to see:
"version": "2.4.0"

#### How to reproduce

Get source code archive from releases github tab, v2.4.0, download, unzip and open package.json

**Comment by acelaya** [comment]
That's actually not used for anything. The version field serves no purpose on apps. It's used on packages when publishing on a registry like npmjs.com

I set the value to 2.3.0 some time before that version was published, when one day I happened to find out it had the value set to 1.0.0 and I never remembered to update it.

It seems like, after that, I forgot to ever update it again 😅

I will just remove the field to avoid further confusions, but you are good. That asset belongs to v2.4, despite what package.json says 🙂
