### ISSUE TITLE
Display statistics by tags

### ISSUE THREAD

**Issue by smalot** [shlinkio/shlink-web-client#261]
Hi !

It could be awesome to view statistics for links grouped by tags.
I mean, in some cases, multiple links can be created for a specific goal/case. Using tag can be useful to group them, and in that case, generating statistics could be a great feature.

Many thanks for you work !

**Comment by acelaya** [comment]
Hey @smalot.

I can confirm the feature will be part of v2.5.0, as the implementation is almost finished.

However, it will require using Shlink v2.2.0 or newer, as the endpoints that provide tha visit stats by tag have been added in that version.

I'm trying to prepare a video showing how it works, but I recently updated my OS, and the video capture software I was using, no longer works :sweat_smile: 

I will share it as soon as I find a working alternative.
