### ISSUE TITLE
Prevent 0.5 steps where numbers just can be in [Z+]

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#262]
#### Shlink web client version

* Version: 2.4.0
* How do you use shlink-web-client: self-hosted

![Shlink](https://user-images.githubusercontent.com/17692860/80800885-fa675a80-8baa-11ea-90ee-5cf6383bac83.PNG)
Its impossible to call a site just 0.5 times so the scale should not show 0.5 steps

**Comment by acelaya** [comment]
The chart library does this when the value to display is too small. Apparently it does it to display more steps.

In theory it can be configured, but I think I tried to enforce it to use a minimum value of 1 for the step, and it didn't work as expected.

I don't remember exactly what was wrong. I will take another look at it.

**Comment by acelaya** [comment]
This seems to be the solution https://stackoverflow.com/a/55863118

I will try it later.

**Comment by acelaya** [comment]
I have just verified that config option does fix it.

This is how it looks without it:

![image](https://user-images.githubusercontent.com/2719332/81276146-ead88d80-9052-11ea-9a11-785ada5f66bb.png)

And this is how it looks when `precision: 0` is set:

![image](https://user-images.githubusercontent.com/2719332/81276212-00e64e00-9053-11ea-8644-128457c9c9d9.png)

The fix will be included in v2.5.0
