### ISSUE TITLE
/rest/v2/mercure-info triggers 404 if not using mercure

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#279]
#### Shlink web client version

* Version: 2.5.0
* How do you use shlink-web-client: self-hosted

#### Summary

`shlinkdomain.com/rest/v2/mercure-info` gets called even if not using mercure.

#### Expected behavior

Depending on if mercure is getting used or not it should be called or not as calling it when not using will trigger errors in dev-console

**Comment by acelaya** [comment]
That's the expected behavior.

Calling that endpoint is the mechanism for the client to know if the server either supports Mercure or has it configured at all.

If a 404 is returned, the client does not try to bind to Mercure.

**Comment by acelaya** [comment]
Hey @MartinH0, I have just released [v2.5.1](https://github.com/shlinkio/shlink-web-client/releases/tag/v2.5.1), with a few improvements and fixes on features released with v2.5.0

Among other things, if you completely disable real time updates from the settings, it will not even try to perform this call.

![image](https://user-images.githubusercontent.com/2719332/83942264-61071600-a7f2-11ea-8d7a-88f0dba0ff6e.png)
