### ISSUE TITLE
Links to releases in Client

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#289]
I would love it if the version-infos would directly link to the release page.
I'm talking about this:
![Shlink VersionInfo](https://user-images.githubusercontent.com/17692860/86836134-5c59aa00-c09d-11ea-82ab-2b421f10cc25.PNG)

Client should link to: https://github.com/shlinkio/shlink-web-client/releases
Server should link to: https://github.com/shlinkio/shlink/releases

So it would be much more comfy to check.
Links should be:

- clickable (lol)
- `rel="noopener noreferrer"` (as its a different domain as the client is atm

Thats it. Should not be hard to implement. Mostly template editing

**Comment by acelaya** [comment]
Pretty useful and easy to implement :-)

Thanks for the suggestion.
