### ISSUE TITLE
Show WebClient version as soon as possible.

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#293]
ATM the version of Server and Client is shown just when you enter a Server.
Makes sense for the Server-Version. But the WebClient version can be shown as soon as possible and even before loging in a server.

Start:
![Start (no version)](https://user-images.githubusercontent.com/17692860/90187414-04a81000-ddba-11ea-837c-993178da110e.PNG)
No Version info, but could show "Client vx.x.x"

Logged in Server:
![Server (with version)](https://user-images.githubusercontent.com/17692860/90187454-17224980-ddba-11ea-9ff3-088a37557b3a.PNG)
With needed versions 👍

**Comment by acelaya** [comment]
Yep, it makes sense. I have considered it too.

**Comment by the-hotmann** [comment]
Also another recommendation:

ATM it is like this:

`Client: v2.5.1 - Server: v2.3.0`

More clever would be:

`Server: v2.3.0 - Client: v2.5.1` (other order, first Server, then Client as this is fixed on right side for desktop)

As then the div could be fixed and would not change if "Server version" are provided.So there would be not difference for the position of "Client version". Hope you understand what I mean.

And in the "Setting" also the version is not provided. Maybe this should be implemented everywhere.

**Comment by acelaya** [comment]
All done!

Client version now is always displayed, regardless the section. In fact, it will show in future sections if added, as the element is now in a parent element.

The server version is then dynamically displayed only if you are connected to any of them.

This will be part of v2.6.0
