### ISSUE TITLE
Consider adding translations to other languages

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-web-client#31]

**Comment by ToneLune** [comment]
Hello,

Are there plans to make localization easier?

Thank you for this simple and effective application.

**Comment by acelaya** [comment]
Thanks for the kind words :)

I'm not completely against adding translations to other languages. However, I've done it for other projects in the past, and for OSS projects it's trickier than it seems. 

First, you need to find the right tool where people can easily contribute translations. If the process is too complex, or they need to go through a long sign-up, or there's any other blocker that can scare people, they will just not do it. Also, that tool needs to be free (or close to free) for obvious reasons.

Second, I will never know how good those translations are. By definition, people will be contributing with languages I don't know, which is always a small risk.

And third, translations get quickly outdated. While the project grows, new strings will be needed, and existing ones will change. That makes supported languages to start getting mixed with literals in the default language, which usually looks ugly and makes users loose trust in the project.

Because of that, I have usually spent my time on other stuff which adds a bigger or longer term value to the project.

**Comment by ToneLune** [comment]
I agree with you.

I am not a programmer, I thought that a file containing all the occurrences to translate, but I understand that this is not so simple to maintain.

Thank you for taking the time to respond, and congratulations again!

**Comment by skys215** [comment]
Hi, @acelaya 
How about just providing a way to translate by user itself (or download from wherever user finds it), but not providing inside the project? In that case, user can just simply replace the file or set the path to the translation file to load different language (single language).
