### ISSUE TITLE
checkbox is hiding the calendar

### ISSUE THREAD

**Issue by Shimakuchi** [shlinkio/shlink-web-client#311]
#### Shlink web client version

* Version: 🤷🏻‍♂️   latest, i guess
* How do you use shlink-web-client: **app.shlink.io**

#### Summary

![image](https://user-images.githubusercontent.com/2376419/94122552-fcc89a80-fe52-11ea-8ceb-2b941db6df81.png)

#### Current behavior

The "Use existing URL if found" checkbox is overlapping the calendar

#### Expected behavior

The Calendar should fully visible

```css
.react-datepicker-popper {
z-index: 9999;
}
```

#### How to reproduce

click the "Enabled until..." calendar field in the "Create short URL" Dialog on a smaller browser window
https://app.shlink.io/server/{yourid}/create-short-url

**Comment by acelaya** [comment]
Ouch. That's not nice 😅

Do you want to contribute the fix?

**Comment by acelaya** [comment]
Fixed!

**Comment by Shimakuchi** [comment]
> Do you want to contribute the fix?

Ah missed that one, sorry ☹️ next time

> Fixed!

Thanks
