### ISSUE TITLE
default text which tells how long the links valid

### ISSUE THREAD

**Issue by Shimakuchi** [shlinkio/shlink-web-client#313]
The user could define a text in the settings, which gets also copied to the clipboard after creating the link. 

example for a default text: `This link is valid until {until_date}`(working with some variable here could maybe helpful in future)

So the text which gets copied to the clipboard would something like

```
This link is valid until 2020-10-08
https://link.to/whatever
```

maybe you could work with localisation here so the inserted date value gets the right format for the users country (08.10.2020 in Germany for example)

**Comment by acelaya** [comment]
I'm afraid I have to say no to this. It would bring a lot of complexity for very small benefit.
