### ISSUE TITLE
A GET manifest.json returns 401 error if page is protected by Basic Auth

### ISSUE THREAD

**Issue by jenkin** [shlinkio/shlink-web-client#316]
#### Shlink web client version

* Version: 2.6.0
* How do you use shlink-web-client: self-hosted
* Browser: Chromium version 83.0.4103.116 (Build) built on Debian 10.4, running on Debian 10.6 (64 bit)

#### Summary

If the web application is protected by Basic Authentication, all requests to `manifest.json` failed with a 401 error, also after authentication. But if you directly access `/manifest.json`, it works without issue.

#### Current behavior

Behind Basic Authentication, requests to `manifest.json` raise a 401 error.

#### Expected behavior

No errors, manifest is loaded without issues.

#### How to reproduce

Install shlink web client. Protect the directory using Basic Auth. Browse to the webpage, enter valid credentials, see the described error in console.

#### Hint for a solution

From [this comment](https://github.com/koajs/basic-auth/issues/19#issuecomment-437050887), add `crossorigin="use-credentials"` attribute to manifest link in `index.html`.

**Comment by acelaya** [comment]
Fixed! Thanks for the hint :slightly_smiling_face:
