### ISSUE TITLE
Allow configuration of base url via environment variable

### ISSUE THREAD

**Issue by stv0g** [shlinkio/shlink-web-client#317]
This would significantly simplify the deployment via Docker images

**Comment by acelaya** [comment]
Hey @stv0g 

Yes, that would be nice, but sadly, it's not possible.

The base path has to be set at build time, as it needs to be replaced in several places. Once built, it cannot be changed at runtime, therefore, there's no way to pass it as an env bar to an already built docker image.

This is a limitation on the tooling used by the project.

You can find the steps to build the docker image yourself with a different base path here https://github.com/shlinkio/shlink-web-client#serve-project-in-subpath
