### ISSUE TITLE
QR Modal Link Wrapping

### ISSUE THREAD

**Issue by antwonw** [shlinkio/shlink-web-client#417]
This line in the CSS specifically states to not wrap the QR Code hyperlink in the QR modal.

https://github.com/shlinkio/shlink-web-client/blob/23ba140ff42530442f14eee5b563aa7a79d617b9/src/index.scss#L162-L164

This results in really bad design behavior.

<img width="625" alt="Screen Shot 2021-05-06 at 4 33 31 PM" src="https://user-images.githubusercontent.com/519934/117378561-94cb3f80-ae8a-11eb-82ba-25b85a7f6d16.png">

Removing these lines fixes the problem.

<img width="535" alt="Screen Shot 2021-05-06 at 4 33 50 PM" src="https://user-images.githubusercontent.com/519934/117378640-b2000e00-ae8a-11eb-9d31-6706f59d5c99.png">

**Comment by antwonw** [comment]
After review, removing the `indivisible` class wholly, would break other instances where `nowrap` is needed.

Instead, the `indivisible` class should be removed from this line.

https://github.com/shlinkio/shlink-web-client/blob/2952ac8892a43afcd52d3d307d57fdc653e03a17/src/short-urls/helpers/QrCodeModal.tsx#L94

**Comment by antwonw** [comment]
I have created a pull request (https://github.com/shlinkio/shlink-web-client/pull/418) to review which removes ` className="indivisible"` from `QrCodeModal.tsx`.

**Comment by acelaya** [comment]
Nice catch. Thanks!
