### ISSUE TITLE
How to Create Server and API key in app.shlink.io?

### ISSUE THREAD

**Issue by dt2036** [shlinkio/shlink-web-client#425]
How to generate a Server? we face the below error: Oops! Could not connect to this Shlink server.
Make sure you have an internet connection, and the server is properly configured and online.

![image](https://user-images.githubusercontent.com/69676290/118135910-2ace0f80-b421-11eb-936a-53730b67e0b4.png)
and when we use the existing API key then give an invalid API key error.

![image](https://user-images.githubusercontent.com/69676290/118136002-420cfd00-b421-11eb-8a3b-e8945c256de2.png)

Thanks in advance.

**Comment by acelaya** [comment]
Duplicates https://github.com/shlinkio/shlink-web-client/discussions/424
