### ISSUE TITLE
[Question] why does randomyl sometimes pops up?

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#454]
#### Shlink web client version

* Version: 3.1.2/3.2.0
* How do you use shlink-web-client: self-hosted

#### Summary

This message sometimes pops up for no reason I can see:
![image](https://user-images.githubusercontent.com/17692860/125345214-8c92f300-e358-11eb-988e-37b297e600c2.png)

Also I must notice I just updated to v3.2.0 and while this message popped up i saw it still was on 3.1.2. After a hardreload it anyway always is gone. But after hard reload I also now saw the new 3.2.0 version on the bottom.

Maybe this is an additional request for forcing a new version to delete the local cache from the old one. Would be awesome.

**Comment by acelaya** [comment]
This is part of the progressive web application capabilities that were re-introduced in v3.1.2.

The app has an offline copy, that ensures it can be loaded faster, and potentially, even without internet.

It also allows you to install the app in a device as if it was a native app.

This offline copy tries to download any available newer version of the app in the background, and displays this message when it happens, just to let you know and make it more predictable.

In v3.2, the message has been improved including a button to manually reload to the new version, without having to close the tabs.
