### ISSUE TITLE
shlink-web-client not saving added servers

### ISSUE THREAD

**Issue by fostermi** [shlinkio/shlink-web-client#455]
#### Shlink web client version

* Version: 3.2.0
* How do you use shlink-web-client: Docker image

#### Summary

When accessing the web-client, after adding a server to the configuration, and then closing the browser, when I open the web-client again, it doesn't have any configured server attached to it. In the logs I see this message:

`2021/07/28 20:32:27 [error] 36#36: *8 open() "/usr/share/nginx/html/conf.d/servers.json" failed (2: No such file or directory)`

I'm not sure if its looking for a pre-configured servers.json file (which I haven't used). According to the documentation, the web-client should "save locally" any added server, but I don't see how that is working unless it writes those to a file or database.

#### Expected behavior

After adding a shlink server to the web-client, when I close the browser and then open it up again, I should see my configured server.

#### How to reproduce

1. Deploy shlink-web-client as a Docker container
2. Navigate to the address of the client
3. Add a shlink server
4. Close browser
5. Open browser and navigate back to web-client

**Comment by acelaya** [comment]
The servers file is only tried to be loaded when no servers are locally found, so that part is working as expected.

This app saves configured servers in the browser's local storage. Are you maybe clearing it or using an incognito navigation?

**Comment by fostermi** [comment]
Ah, ok. I thought "locallly" mean on disk inside the container. I was using incognito mode.

**Comment by acelaya** [comment]
Nop, shlink-web-client is a client-side app, so there's no storage of any kind server side.

I'll review the docs to make sure this is clear and avoid future confusions.
