### ISSUE TITLE
Possible to enable dark mode at runtime without making the dark mode selection - default dark.

### ISSUE THREAD

**Issue by mannp** [shlinkio/shlink-web-client#456]
Hi there :)

#### Shlink web client version

* Version: 3.2.0
* Docker image|self-hosted

#### Summary

I wondered if there is a way to select the dark theme at runtime in an ENV var or other means for docker at all? 

I go into the gui and immedaitely go to settings / dark each time :) and wondered if I was missing a setting.

Not seen anything looking through github here...

**Comment by acelaya** [comment]
The settings are saved in the browser's local storage.

As long as you don't clear it or use an incognito session, your selected value should persist.

**Comment by mannp** [comment]
> The settings are saved in the browser's local storage.
> 
> As long as you don't clear it or use an incognito session, your selected value should persist.

Oh I see, thanks, I will see how to disable all of my cookie removers for shlink web, cheers.
