### ISSUE TITLE
Allow editing matadata from existing URLs

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-web-client#46]
Data that can be edited from a URL is

* Valid since
* Valid until
* Max visits

This won't work with shlink previous than 1.18, so UI controls should be dynamically displayed only if this info was returned.

**Comment by 2114L3** [comment]
this would allow published short links to be maintainable when hosts change
the web client can achieve an edit with the current API. but maybe including the long url in the meta edit API function would allow easy scripted bulk changes eg. if a repo/cdn is moved folder or host.
obfuscating sysadmin changes or missing perma link functionality would be fantastic 

along with edit, a simple lock meta to protection against accidental deletes or edits would be nice.
