### ISSUE TITLE
Short URLs list shows no results when filtering by a tag with special chars

### ISSUE THREAD

**Issue by tedo-develop** [shlinkio/shlink-web-client#478]
Hello Acelaya,

we have tested the new version and found a new feature.
If you search on page "manage tags" for example sigmatek-gmbh-&-co-kg you will get the correct tag. 
But if you click on "Short-URLs" the tag los any chars after "&". The function "Visits" works as expected.

1. Search works
![Screenshot 2021-08-31 at 08 46 31](https://user-images.githubusercontent.com/39614855/131457397-33ee009c-6c23-43b8-bab7-1eefb04d548b.png)

2. Click on Short-URLs
![Screenshot 2021-08-31 at 08 46 38](https://user-images.githubusercontent.com/39614855/131457437-96410f18-537a-485f-87d6-ddfff61fcef3.png)

3. No Results
![Screenshot 2021-08-31 at 08 46 45](https://user-images.githubusercontent.com/39614855/131457464-a3c3588d-33a2-43b3-ae9d-3bbe4dd222ea.png)

Thanks for your work!

_Originally posted by @tedo-develop in https://github.com/shlinkio/shlink-web-client/discussions/458#discussioncomment-1257892_

**Comment by acelaya** [comment]
The problem was that the tag, which is sent as a query param to the other section, was not properly URL-encoded, making the `&` be considered as the split for a second query param.
