### ISSUE TITLE
Add option for "All visits" at "Default interval to load"

### ISSUE THREAD

**Issue by the-hotmann** [shlinkio/shlink-web-client#496]
#### Summary

I love the option to set the option of what the default scope. But I am missing the option to set it to "All visits" what would be this option:

![image](https://user-images.githubusercontent.com/17692860/134828743-c1b7f666-0674-408e-a495-e72f7fd469db.png)

This atm cant be default, but I´d wish I would set it.

**Comment by acelaya** [comment]
This is now implemented and will be included in shlink-web-client 3.4.0
