### ISSUE TITLE
Title is not removable

### ISSUE THREAD

**Issue by cyb3rko** [shlinkio/shlink-web-client#503]
#### Shlink web client version

* Version: v2.8.1
* How do you use shlink-web-client: app.shlink.io

#### Summary

It seems that the web client currently doesn't allow you to remove the title of a short url.
The problem is clearly client-side as editing and removing the title works directly through the api.

#### Current behavior

If you have a title set and you try to remove it on the edit page, it says 'Short URL properly edited.' but if you go back to the url overview, the title is still there.

#### Expected behavior

I tried to remove the title but simply leaving the title field empty, which I think is how it should be done, right?

#### How to reproduce

1. Have / Add a title on any short url.
2. Try to remove it by leaving empty the title input field and saving the changes.
3. Go back to the url overview and find the previous title again.

**Comment by acelaya** [comment]
I have just released v3.3.2, which includes a fix for this.

As soon as [this workflow](https://github.com/shlinkio/shlink-web-client/runs/3918341525?check_suite_focus=true) finishes, I will publish it to app.shlink.io

**Comment by cyb3rko** [comment]
Awesome, thanks!
