### ISSUE TITLE
Duplicate server import

### ISSUE THREAD

**Issue by cyb3rko** [shlinkio/shlink-web-client#506]
#### Shlink web client version

* Version: 3.3.1
* How do you use shlink-web-client: app.shlink.io

#### Summary

Currently it is possible to add duplicate server entries.

#### Current behavior

If you add a server which is already added it just adds a duplicate server entry.

#### Expected behavior

If you try to add a server which is already added there should be a warning that it's already added.
If you add the same server via csv import it could be ignored to not add it again.

#### How to reproduce

Import a server you have already added to your client, either by manually typing in the details or via csv import.
It will just add the server again, although it already exists.

**Comment by acelaya** [comment]
This is now implemented and will be part of shlink-web-client 3.5.0

Now, when you create a server, if there's already another one with the same URL and API key, a warning will be displayed, allowing you to discard the changes, or save the server anyway.

Similarly, when importing a list of servers, a warning will be displayed with all that already exist. The warning will allow you to create all servers anyway, or just create non-existing ones, discarding duplicates.

**Comment by cyb3rko** [comment]
Happy new year!

Awesome, thank you.
