### ISSUE TITLE
Allow providing a custom slug from basic creation form in overview section

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink-web-client#531]
I’m currently interested in switching from YOURLS to Shlink, just because it seems so more flexible, faster and simply sexier. 

What I really enjoyed with YOURLS is the very usable interface: When you're landing on the backend (=web interface), you're able to simply enter the long URL and a customised short URL right away. If you leave the custom shortlink blank, it will generate one for you.
With the Shlink web interface, I have to click on the _Advanced Options_ before I can customise my short URL, and then I a _forced_ to enter a custom title as well, otherwise the interface is returning an _Unknown Error_. 

It would be absolutely lovely if I could simply access the web interface home page, enter my long URL and my shortlink and don’t have to click further and enter a mandatory Title for it, especially when I am trying to add a lot of links one after another.

**Comment by acelaya** [comment]
I have finally transferred this issue so that you only have to open a new one for the title thing, if you want to dig deeper into it.

**Comment by enoversum** [comment]
@acelaya Hi Alenjandro, first of all, thanks for taking care of my requests so quickly. I had misplaced this on the wrong project – I used the shlink.io official interface for testing with my first domain and kind of thought it as part of Shlink. Gotcha!
I'll open another issue for the title thing again 🙂. Thanks for this lovely app, by the way!

**Comment by enoversum** [comment]
Just a slight update – can’t reproduce the Title error anymore. When I now add links through the advanced interface for link addition, leaving out the title doesn't produce an unknown error anymore. Before, it had created a bunch (not the one that appears on loading of the page) of 501 errors on the REST API, so console said.

**Comment by enoversum** [comment]
@acelaya Okay, as per your request, asking here again: Is this feature request something rather on the back of your roadmap, and/or a longer and more complex task? 
I'm not wanting to rush you, really, just interested because that is something that YOURLS really excels at, entering new, customised shortlinks very quickly. Having this in Shlink (as an option, to keep the old setting for those who love the current solution) would absolutely convince me to finally make the leap. 

If I in one or another way can help – let me know.

**Comment by acelaya** [comment]
No, it's not something complex.

However, my efforts are currently focused on Shlink v2.10, and won't be working on a feature release for shlink-web-client before that is released.

As per timing, absolutely no idea 🙂, but probably a couple of months until this is released.

**Comment by enoversum** [comment]
@acelaya Okay, got it completely. Happy if you’ll at some point be able to bake this in then – good luck with the 2.10 release then!

**Comment by acelaya** [comment]
This is now implemented and will be part of shlink-web-client v3.5.0

![image](https://user-images.githubusercontent.com/2719332/146674072-bc6932b1-c847-4543-b519-e98388a2a1da.png)

**Comment by enoversum** [comment]
@acelaya That's beautiful, thank you. Not meaning to rush you, just interested - any plans on when to release it? I know you wrote 'several months', as you wanted to focus on shlink itself and the 2.10 release. Just feels you prioritised this now ♥.
Edit: Just realised 2.10 is out already. Wow!

**Comment by acelaya** [comment]
Yes, I'm now primarily working on Shlink-web-client 3.5.0, but I don't know when will it be released.

Usually every release of any of the two projects takes me around 1-2 months, as I can work mainly on weekends, and only if I feel like it, haha.

The difference is that I have some holidays in the next couple if weeks. That could mean either I have more time to work on this, or I have more plans with friends and family, and therefore less time. So I cannot possibly tell for sure.

It will be released... Eventually. Q1 2022 😅

**Comment by enoversum** [comment]
@acelaya Ah, thanks for clearing that up. I certainly don’t want to rush, and I already understood you're mostly working on weekends on the project. And life should always come first, so take your time and _do_ see friends and family, please!
