### ISSUE TITLE
New tags do not appear in autocomplete

### ISSUE THREAD

**Issue by Roy-Orbison** [shlinkio/shlink-web-client#557]
#### Shlink web client version

* Version: 3.5.0
* How do you use shlink-web-client: app.shlink.io

#### Summary

Newly created tags are not shown in the autocomplete suggestions of other URLs.

#### How to reproduce

1. Go to the editor of an existing short URL
2. Add a tag that doesn't yet exist in the database
3. Save the change
4. Go to the editor of another existing short URL
5. Start typing the tag from step 2

#### Current behavior

The new tag does not appear as an autocomplete suggestion

#### Expected behavior

It should appear as a suggestion

#### Workaround

Reload the web app for it to become aware of the new tag. It will then autocomplete as expected.

**Comment by acelaya** [comment]
I have just released shlink-web-client 3.5.1, which includes a fix for this bug.

Once [this build](https://github.com/shlinkio/shlink-web-client/actions/runs/1671046469) has finished, I will update the version in app.shlink.io
