### ISSUE TITLE
Allow excluding visits tracking from logged-in users

### ISSUE THREAD

**Issue by enoversum** [shlinkio/shlink-web-client#559]
At the moment, even if you're clicking a link as a logged-in user directly in the web UI, Shlink tracks this as a visit. It would help if one could exclude link tracking for any logged-in user.

**Comment by acelaya** [comment]
There's no such thing as "logged-in" user.

The simplest option here would be to not really link to short URLs, but you can also try not to click on them 😅 

It's a bit of an edge case.

**Comment by enoversum** [comment]
Understood. Traditional backends don't rely on browser cache, that's what your web client does if I got it right, but often on cookies. Those would then be cross-linked and excluded, but I assume you know that 😉. I get that's not applicable to shlink.
