### ISSUE TITLE
Docker web client not loading on :latest tag

### ISSUE THREAD

**Issue by snorkrat** [shlinkio/shlink-web-client#617]
#### Shlink web client version

* Version: :latest
* How do you use shlink-web-client: Docker image

#### Summary

I did a fresh pull of the webui which in my compose file was set to use the :latest tag.  After that, the webui would not load.
I see the background colour change, but nothing else is displayed.

When in chrome under console I get:

```
store.ts:17 Uncaught TypeError: $R is not a function

at store.ts:17:55

at index.tsx:34:20

at index.tsx:34:20
```

And under the elements tab I get:
```
<noscript>You need to enable JavaScript to run this app.</noscript>
```
I have checked chrome settings and JavaScript is enabled and not disabled for any specific sites.  Also going to https://www.whatismybrowser.com/detect/is-javascript-enabled confirms JavaScript is working.

Changing back to the :stable tag (v3.6.0) and it loads properly.

#### Current behavior

webui does not load

#### Expected behavior

webui should load
#### How to reproduce

change tag from :stable to :latest and restart docker container.

**Comment by MrPvTDagger** [comment]
I'm experiencing the same behavior with the latest tag.

**Comment by acelaya** [comment]
It should be fixed.

Can you check again once https://github.com/shlinkio/shlink-web-client/actions/runs/2081250028 has finished? Should take around 30min.

**Comment by snorkrat** [comment]
Working as expected now.  Thanks :)
