### ISSUE TITLE
Add sorting to country graph

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink-web-client#65]
It would be a nice feature to either sort the country stats graph by quantity of visits and in the future if time permits, alphabetically. As of right now it seems to sort by first click date.

https://i.imgur.com/rXVaMg8.png

**Comment by acelaya** [comment]
This is a nice addition and shouldn't be hard to implement, so count on it.

**Comment by acelaya** [comment]
It is already implemented and will be part of next release.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2719332/47622240-092b0800-db03-11e8-9e7e-60224ad171d5.gif)

As you can see, it will be possible to order both by **country name** and by the **amount of visits**, both ascendant and descendant.

I have added this to the referrers graph as well.

**Comment by acelaya** [comment]
@tivyhosting Just released v1.2.0 which includes this feature.

It is also available in https://app.shlink.io
