### ISSUE TITLE
Bug with tooltips on the country stats graph when there is a large difference in visits between countries

### ISSUE THREAD

**Issue by jakkuh** [shlinkio/shlink-web-client#66]
When there is a large difference in visits between countries, it can be very difficult to see what the click count is on countries on the small side of that.

This is because the tooltip is set to only appear when hovering over the bar and not the Y axis label itself.

Potential solutions:
1. Have the tool tip appear also when hovering over the respective Y axis label
2. Show a click count at the end of each bar

https://i.imgur.com/zkPdif2.png

**Comment by acelaya** [comment]
Since I'm using a third party library to render the graphs, I'm not 100% sure how difficult this could be, but I'll try to provide a solution.

Thanks!

**Comment by acelaya** [comment]
@tivyhosting this is the best solution I could get after some time digging in ChartJS docs.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2719332/47745463-04da2880-dc84-11e8-9748-7165c2063a26.gif)

Also, it behaves quite well in mobile devices, since you can click anywhere.
