### ISSUE TITLE
[BUG] Version: 3.7.1: Incorrect link generation in UI when using default domain

### ISSUE THREAD

**Issue by DerPhlipsi** [shlinkio/shlink-web-client#674]
#### Shlink web client version

* Version: [3.7.1](https://github.com/shlinkio/shlink-web-client/releases/v3.7.1)
* How do you use shlink-web-client: app.shlink.io

#### Summary

After switching to the current version of the App, the short-links displayed/generated in the Overview and short-URL list are invalid, if the short link does not have a specific domain configured. Any short-URL using the default setting is broken, any short-URL with a specific domain set is shown and works correctly.

#### Current behavior

Links without a specific domain set only generate the parts "https:/" and the short-link itself. E.g. "https:/ABC123". Links with a domain set generate correctly.

#### Expected behavior

Links work regardless of the domain setting.

#### How to reproduce

Access Shlink server with the Shlink App version 3.7.1 that has short-links without any domain specified / using the default setting.

#### Examples:

Shlink instance only using a default domain:
![wIkEHcco9z](https://user-images.githubusercontent.com/15906070/173835167-ead42155-4b36-4686-aeab-681087740c64.png)

Shlink instance using a default domain as well as selected domains:
![bv39qxCBLC](https://user-images.githubusercontent.com/15906070/173835271-8a339c36-726c-4fea-b393-b1bde87a64b3.png)

**Comment by acelaya** [comment]
Not a bug on the client. You probably didn't set the DEFAULT_DOMAIN env var.
