### ISSUE TITLE
Allow time to be specified when setting limit for link to be enabled

### ISSUE THREAD

**Issue by kouyk** [shlinkio/shlink-web-client#717]
#### Summary

Currently the web client allows the user to control when the link is enabled, but only the date can be specified. From a brief look at the API, the granularity allows for the time to be specified as well. Is it possible for this to be exposed in the web client as well?

**Comment by acelaya** [comment]
I need to check if the API actually honors provided time (I'm almost sure it does, but this was implemented long ago).

If so, yes, supporting this should be possible, as the date component supports time as well.

**Comment by acelaya** [comment]
I can confirm Shlink does indeed support this already. It just requires the changes in the UI.

**Comment by acelaya** [comment]
How do these look:

* Dark theme: https://youtu.be/w6vb3du7mHg
* Light theme: https://youtu.be/dDQ7Lwibvgo

The time component will allow you to pick in 10 minute intervals.

**Comment by kouyk** [comment]
> How do these look:
> 
>     * Dark theme: https://youtu.be/w6vb3du7mHg
> 
>     * Light theme: https://youtu.be/dDQ7Lwibvgo
> 
> 
> The time component will allow you to pick in 10 minute intervals.

Looks great, 10 minute intervals should be sufficient granularity under most circumstance.
