### ISSUE TITLE
Short URLs list can't turn pages, filter and search

### ISSUE THREAD

**Issue by sxjeru** [shlinkio/shlink-web-client#718]
#### Shlink web client version

* Version: [3.7.3](https://github.com/shlinkio/shlink-web-client/releases/v3.7.3)
* How do you use shlink-web-client: app.shlink.io

#### Summary

All in the title. I can't do the following on page "List short URLs":
- Go to Page 2
- Sort by header
- Search by text or tag
- Filter by time

Considering that there may be performance concerns. I also try to add Redis to the shlink in Docker. 
But according to the document, I don't know how to fill in the password of Redis.
I have tried to fill `password@server:port` in the `REDIS_SERVERS` environment variable, it failed.

Thanks for any support!

**Comment by acelaya** [comment]
Can you share a recording to see what you mean? What browser are you using? Does the browser console show any error?

**Comment by sxjeru** [comment]
I tried PC chrome (106.0.5249.91), Edge and Android Chrome, and they all had the problem.

The console will output after each refresh: 
`GET https://[domain]/rest/v2/mercure-info 501`

The following sentence appears many times when staying on the page:
`Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

When I turn page or search, the console does not give any errors.

[Recording](https://user-images.githubusercontent.com/20513115/197119044-a4e5e080-8147-445c-8300-385114ab483c.mp4)
