### ISSUE TITLE
Preparation for v4.0.0

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-web-client#812]
This is like a wishlist of things that would make a nice v4.0.0 release.

### Migrate from bootstrap to tailwind

I have started to use tailwind recently, and now I miss it when it's not available.

This would be a huge change though, as all the components would need to be rewritten.

I also need to explore if a migration in stages is possible, or it needs to be all or nothing.

### Get ready for Shlink dashboard 🟢

I have been delaying this for literally years, but getting this project ready to eventually start working on Shlink dashboard, would add a lot of value.

The problem is that it's relatively complex, and it's always been delayed to work on basically supporting all new features added to Shlink.

Ref: https://github.com/shlinkio/shlink-web-client/issues/338

### End to end tests with playwright

Another one that has been delayed for years. E2E tests with playwright would cover some cars that are not easy to test with unit/integration tests

Ref: https://github.com/shlinkio/shlink-web-client/issues/145

### Drop support for old Shlink versions 🟢

This is done regularly, so no that critical, but a new major version of shlink-web-client should drop support to anything older than Shlink 3.0.0, at least.

### Implement visits comparison capabilities 🟢 

For a long time there have been plans to implement visits-comparison capabilities, but their complexity has delayed them indefinitely: See https://github.com/shlinkio/shlink-web-component/issues/9 and https://github.com/shlinkio/shlink-web-component/issues/7

Something like this would be very beneficial, as it's important to be able to see how some short URL evolves over time, as well as compare which perform better.

**Comment by danielthedifficult** [comment]
@acelaya Hi, long time!

I'm wondering if you're interested in localization at all. Would you be open to adding i18n or something like that to have Shlink available in multiple languages?

**Comment by acelaya** [comment]
> @acelaya Hi, long time!
> 
> I'm wondering if you're interested in localization at all. Would you be open to adding i18n or something like that to have Shlink available in multiple languages?

@danielthedifficult hope this answers your question https://github.com/shlinkio/shlink-web-client/issues/31#issuecomment-583898424 🙂

**Comment by acelaya** [comment]
Migrating to tailwind and adding E2E tests will be delayed, as v4.0.0 has been in the works for around 9 months
