### ISSUE TITLE
RabbitMQ

### ISSUE THREAD

**Issue by fessnecro** [shlinkio/shlink-web-client#835]
I have enabled rabbitMQ and its not works at all... AbstractNotifyVisitListener does not fires. Maybe I miss something?
My config:

    'DB_DRIVER' => 'postgres',
    'DB_NAME' => 'shlink',
    'DB_HOST' => 'shlink_db_postgres',
    'DB_PORT' => '5432',
    'DB_USER' => 'postgres',
    'DB_PASSWORD' => 'root',
    'DEFAULT_DOMAIN' => 's.localhost',
    'IS_HTTPS_ENABLED' => false,
    'DEFAULT_SHORT_CODES_LENGTH' => 5,
    'AUTO_RESOLVE_TITLES' => false,
    'REDIRECT_APPEND_EXTRA_PATH' => false,
    'MULTI_SEGMENT_SLUGS_ENABLED' => false,
    'SHORT_URL_TRAILING_SLASH' => false,
    'SHORT_URL_MODE' => 'strict',
    'GEOLITE_LICENSE_KEY' => '123',
    'REDIRECT_STATUS_CODE' => 302,
    'DISABLE_TRACKING' => false,
    'TRACK_ORPHAN_VISITS' => true,
    'DISABLE_TRACK_PARAM' => null,
    'DISABLE_TRACKING_FROM' => null,
    'DISABLE_IP_TRACKING' => false,
    'ANONYMIZE_REMOTE_ADDR' => true,
    'DISABLE_UA_TRACKING' => false,
    'DISABLE_REFERRER_TRACKING' => false,
    'DEFAULT_BASE_URL_REDIRECT' => null,
    'DEFAULT_INVALID_SHORT_URL_REDIRECT' => null,
    'DEFAULT_REGULAR_404_REDIRECT' => null,
    'DEFAULT_QR_CODE_SIZE' => 300,
    'DEFAULT_QR_CODE_MARGIN' => 0,
    'DEFAULT_QR_CODE_FORMAT' => 'png',
    'DEFAULT_QR_CODE_ERROR_CORRECTION' => 'l',
    'DEFAULT_QR_CODE_ROUND_BLOCK_SIZE' => true,
    'DELETE_SHORT_URL_THRESHOLD' => null,
    'BASE_PATH' => '',
    'TIMEZONE' => null,
    'REDIS_SERVERS' => null,
    'RABBITMQ_ENABLED' => true,
    'RABBITMQ_HOST' => 'shlink_rabbitmq',
    'RABBITMQ_PORT ' => 5672,
    'RABBITMQ_USER' => 'rabbit',
    'RABBITMQ_PASSWORD' => 'rabbit',

**Comment by acelaya** [comment]
Hi @fessnecro.

Please, report this in https://github.com/shlinkio/shlink/issues/new?assignees=&labels=bug&projects=&template=Bug.md, and make sure you fill-in all requested information.
