### ISSUE TITLE
Update to `react-tag-autocomplete` 7

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-web-client#855]
~There's no clear changelog or update path, so this requires a bit of try and error.~ [Migration guide](https://github.com/i-like-robots/react-tag-autocomplete/blob/main/migration-guide.md#changes-to-render-props)

- [x] General migration
- [x] Mimic styles
- [x] Get rid of "Add %value%" option
- [x] Implement addOnBlur (or just remove)
    - test behavior on latest Android, and ignore it if it works reasonably well
- [x] Add on list item click
- [x] Avoid redefining unchanged classes
- [x] Add/Fix tests
- [x] ~Do not toggle tags when adding an already added one~ -> https://github.com/shlinkio/shlink-web-component/issues/1

**Comment by acelaya** [comment]
Blocked by https://github.com/i-like-robots/react-tag-autocomplete/issues/48

**Comment by Shubhamtribhuvan8** [comment]
hey @acelaya  whats an issue #855

**Comment by acelaya** [comment]
What do you mean

**Comment by Shubhamtribhuvan8** [comment]
Update to react-tag-autocomplete 7 #855 is this issue right?so can i contribute for this?

**Comment by acelaya** [comment]
The issue is right, but it is blocked. See above.

I already have a branch with the migration almost done, so no need to contribute.

**Comment by Shubhamtribhuvan8** [comment]
Thanks @acelaya
