### ISSUE TITLE
Set default theme based on system preferred color scheme

### ISSUE THREAD

**Issue by XHyperDEVX** [shlinkio/shlink-web-client#978]
### Summary

I would find it great if, for example, you could use an env in docker to specify that dark mode is activated by default when the page is opened on a new device.

### Use case

It's better for the eyes and the battery ;)

**Comment by acelaya** [comment]
Env vars are very hard to handle on static apps like shlink-web-client.

There's only another case of an env var here, which requires the docker container entry point to write a file, and then takes advantage of another previously existing feature that already tried to download that file and use it if found.

I don't think that's a good approach for the theme default value, as you would still see a flash of light theme until the file was downloaded and processed.

That, together with the complexity to handle the env var, makes it clear that's not a good approach.

What could be done instead, and I have considered many times, is defaulting the theme to the system preferred color scheme.

Considering the theme gets persisted once set for the first time in one device, that should cover it in a nice way.

**Comment by XHyperDEVX** [comment]
It's actually even better this way. Thank you very much!

**Comment by XHyperDEVX** [comment]
@acelaya I see they have implemented it! Thank you very much! When will the next Docker image update be?

**Comment by XHyperDEVX** [comment]
@acelaya?

**Comment by acelaya** [comment]
> When will the next Docker image update be?

Hard to say. I'd suggest to watch for new releases

![image](https://github.com/shlinkio/shlink-web-client/assets/2719332/013c7f5c-f986-46cb-b536-45cd7f79a886)

**Comment by XHyperDEVX** [comment]
@acelaya 
How do you determine this? How do you decide when to update the Docker image?
